package edu.ubb.bsc.repo.model;
// Generated Mar 21, 2016 3:24:25 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SheetmusicComment generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "sheetmusic_comment", catalog = "bscproject")
public class SheetmusicComment implements java.io.Serializable {

	private Integer sheetmusicCommentId;
	private SheetMusic sheetMusic;
	private User user;
	private String comment;
	private Date postedDate;
	
	public SheetmusicComment() {
	}

	public SheetmusicComment(SheetMusic sheetMusic, User user, String comment, Date postedDate) {
		this.sheetMusic = sheetMusic;
		this.user = user;
		this.comment = comment;
		this.postedDate = postedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sheetmusic_commentID", unique = true, nullable = false)
	public Integer getSheetmusicCommentId() {
		return this.sheetmusicCommentId;
	}

	public void setSheetmusicCommentId(Integer sheetmusicCommentId) {
		this.sheetmusicCommentId = sheetmusicCommentId;
	}

	@ManyToOne//(fetch = FetchType.LAZY)
	@JoinColumn(name = "sheetMusicID")
	public SheetMusic getSheetMusic() {
		return this.sheetMusic;
	}

	public void setSheetMusic(SheetMusic sheetMusic) {
		this.sheetMusic = sheetMusic;
	}

	@ManyToOne//(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "comment", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "postedDate", length = 19)
	public Date getPostedDate() {
		return this.postedDate;
	}

	public void setPostedDate(Date postedDate) {
		this.postedDate = postedDate;
	}
	
}
