package edu.ubb.bsc.repo.model;
// Generated Feb 28, 2016 7:22:44 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessorOrder;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * User generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "user", catalog = "bscproject")
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPassword;
	private String userMail;
	private String userTel;
	private Integer userRight;
	private Date userLastLogin;
	private String userFirstName;
	private String userLastName;

	public User() {
	}

	public User(String userName, String userPassword, String userMail, String userTel, Integer userRight,
			Date userLastLogin, String userFirstName, String userLastName) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userMail = userMail;
		this.userTel = userTel;
		this.userRight = userRight;
		this.userLastLogin = userLastLogin;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "userName", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "userPassword", length = 45)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "userMail", length = 45)
	public String getUserMail() {
		return this.userMail;
	}

	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}

	@Column(name = "userTel", length = 45)
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	@Column(name = "userRight")
	public Integer getUserRight() {
		return this.userRight;
	}

	public void setUserRight(Integer userRight) {
		this.userRight = userRight;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userLastLogin", length = 19)
	public Date getUserLastLogin() {
		return this.userLastLogin;
	}

	public void setUserLastLogin(Date userLastLogin) {
		this.userLastLogin = userLastLogin;
	}

	@Column(name = "userFirstName", length = 45)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "userLastName", length = 45)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	public String toString(){
		return "\tuserId: " + userId+
		"\tuserName: " + userName +
		"\tuserFirstName : " + userFirstName +
		"\tuserLastName: " + userLastName +  
		"\tuserMail: " + userMail +
		"\tuserRight: " + userRight;
	}

}
