package edu.ubb.bsc.repo.model;
// Generated Feb 16, 2016 11:58:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Advertisement generated by hbm2java
 */
@Entity
@XmlRootElement
@Table(name = "advertisement", catalog = "bscproject")
public class Advertisement implements java.io.Serializable {

	private Integer advId;
	private User user;
	private String name;
	private String description;
	private Double price;
	private String priceType;
	private Date date;

	public Advertisement() {
	}

	public Advertisement(User user, String name, String description, Double price, String priceType, Date date) {
		this.user = user;
		this.name = name;
		this.description = description;
		this.price = price;
		this.priceType = priceType;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "advID", unique = true, nullable = false)
	public Integer getAdvId() {
		return this.advId;
	}

	public void setAdvId(Integer advId) {
		this.advId = advId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "priceType", length = 45)
	public String getPriceType() {
		return this.priceType;
	}

	public void setPriceType(String priceType) {
		this.priceType = priceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	public String toString(){
		return "\tavdId: " + advId+
		"\tuserBy: " + user.getUserName() +
		"\tavdName: " + name;
	}

}
