package edu.ubb.bsc.repo.model;
// Generated Feb 28, 2016 7:22:44 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Instrument generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "instrument", catalog = "bscproject")
public class Instrument implements java.io.Serializable {

	private Integer instrumentId;
	private String name;
	private String type;

	public Instrument() {
	}

	public Instrument(String name, String type) {
		this.name = name;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "instrumentID", unique = true, nullable = false)
	public Integer getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(Integer instrumentId) {
		this.instrumentId = instrumentId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
