package edu.ubb.bsc.repo.model;
// Generated Feb 28, 2016 7:22:44 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SheetMusic generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "sheet_music", catalog = "bscproject")
public class SheetMusic implements java.io.Serializable {

	private Integer sheetMusicId;
	private SongGenre songGenre;
	private User user;
	private String name;
	private Date uploadDate;
	private Integer length;
	private String license;
	private Integer viewsNum;
	private byte[] fileSound;
	private byte[] filePdf;

	public SheetMusic() {
	}

	public SheetMusic(SongGenre songGenre, User user, String name, Date uploadDate, Integer length, String license,
			Integer viewsNum, byte[] fileSound, byte[] filePdf) {
		this.songGenre = songGenre;
		this.user = user;
		this.name = name;
		this.uploadDate = uploadDate;
		this.length = length;
		this.license = license;
		this.viewsNum = viewsNum;
		this.fileSound = fileSound;
		this.filePdf = filePdf;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sheetMusicID", unique = true, nullable = false)
	public Integer getSheetMusicId() {
		return this.sheetMusicId;
	}

	public void setSheetMusicId(Integer sheetMusicId) {
		this.sheetMusicId = sheetMusicId;
	}

	@ManyToOne//(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_genreID")
	public SongGenre getSongGenre() {
		return this.songGenre;
	}

	public void setSongGenre(SongGenre songGenre) {
		this.songGenre = songGenre;
	}

	@ManyToOne//(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uploadDate", length = 19)
	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	@Column(name = "length")
	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	@Column(name = "license", length = 45)
	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	@Column(name = "viewsNum")
	public Integer getViewsNum() {
		return this.viewsNum;
	}

	public void setViewsNum(Integer viewsNum) {
		this.viewsNum = viewsNum;
	}

	@Column(name = "fileSound")
	public byte[] getFileSound() {
		return this.fileSound;
	}

	public void setFileSound(byte[] fileSound) {
		this.fileSound = fileSound;
	}

	@Column(name = "filePDF")
	public byte[] getFilePdf() {
		return this.filePdf;
	}

	public void setFilePdf(byte[] filePdf) {
		this.filePdf = filePdf;
	}
	
	
	public String toString(){
		return "\tsmId: " + sheetMusicId+
		"\tname: " + name +
		"\tuploadDate: " + uploadDate +
		"\tuser: " + user.getUserName();
	}

}
